
from flask import Flask
from rq import Queue
from redis import Redis
from count_worker import count_words_at_url

app = Flask(__name__)

# Establish a connection to Redis server
redis_conn = Redis()

# Create a queue
q = Queue(connection=redis_conn)

# Route to enqueue the job
@app.route('/')         #a job is enqueued using Redis Queue (rq).
def index():
    # Enqueue a job
    job = q.enqueue(count_words_at_url, 'https://en.wikipedia.org/wiki/Nepal')
   
    return ({'message': 'Job enqueued', 'job_id': job.id}) #response typically includes a message confirming the enqueue operation and the unique job ID generated by Redis Queue.

if __name__ == '__main__':
    app.run(port=8081)
