version: '3.8'

services:
  start:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: start
    command: python start.py
    ports:
      - "8008:8008"  # match the port used in start.py
    depends_on:
      - redis
      - worker
    volumes:
      - ./app:/app
    env_file:
      - ./app/.env

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"  # Host port 6380 maps to container port 6379
    expose:
      - "6379" 

  worker:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: worker
    command: python worker.py
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    volumes:
      - ./app:/app
    env_file:
      - ./app/.env
