version: '3'
services:
  hello:
    build:
      context: ./hello
      dockerfile: Dockerfile
    command: python hello.py
    volumes:
       - ./hello:/app  

  flask:
    build:
      context: ./flask-app
      dockerfile: Dockerfile
    command: python visit_count.py

    ports:
      - "8080:8080"
    volumes:
      - ./flask-app:/app 
    env_file:
      - ./flask-app/.env
     
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

# hello Service: Builds from ./hello directory, using Dockerfile in /hello and runs hello.py.
# flask Service: Builds from ./flask-app directory, using Dockerfile in /flask-app and runs app.py, exposing port 5000.