version: '3'
services:
  hello:
    build:
      context: ./hello
      dockerfile: Dockerfile
    command: python hello.py
    volumes:
       - ./hello:/app  

  flask:
    build:
      context: ./flask-app
      dockerfile: Dockerfile
    command: python visit_count.py

    ports:
      - "8080:8080"
    volumes:
      - ./flask-app:/app 
    env_file:
      - ./flask-app/.env
     
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

#enqueue container:enqueues tasks into Redis that will be proecessed by worker
  enqueue:
    build:
      context: ./rq
      dockerfile: Dockerfile
    command: python enqueue.py
    ports:
      - "8000:8000"
    volumes:
      - ./rq:/app
    depends_on:
      - redis
    env_file:
      - ./rq/.env 

# rq-worker container: processes tasks from Redis queues :listens for tasks and executes them.    
  rq-worker:
    build:
      context: ./rq
      dockerfile: Dockerfile
    command: python worker.py
    depends_on:
      - redis
    volumes:
      - ./rq:/app
    env_file:
      - ./rq/.env 



